### PR TITLE
Fix typos.

### PR DESCRIPTION
**Pull request by AYMENJD**
Legends can easily introduce typos due to their fast coding skills.

### CODE REVIEW

**Comment by levlam** [comment]
Thank you!

**Comment by brent85** [comment]
> Contributor
https://github.com/tdlib/td/pull/2365#issue-1640537847
https://github.com/tdlib/td/pull/2365#issue-1640537847
gh pr checkout 2365

**Comment by brent85** [comment]
gh pr checkout 2365

**Comment by kasatkamaria2-prog** [comment]
> Legends can easily introduce typos due to their fast coding skills.

**Comment by kasatkamaria2-prog** [comment]
> > Legends can easily introduce typos due to their fast coding skills.
> 
>

**Pull request merged**
