### PR TITLE
Add kotlin to examples

### LINKED ISSUE #703: Kotlin implementation
Some time ago I've created [ktd](https://github.com/whyoleg/ktd/tree/develop) - Kotlin auto-generated bindings for tdlib. Now it's JVM only, but may be will make it multi-platform later.
It's now updated to latest(1.5.0) version.
Is it possible to add it to example implementations? If so, I will create PR

### PR DESCRIPTION
**Pull request by whyoleg**
fixes #703

### CODE REVIEW

**Comment by levlam** [comment]
Perfect! I will merge it soon.

**Comment by isopen** [comment]
Cool example. Please demonstrate the operation of the example with a graphic stream.

**Comment by whyoleg** [comment]
@isopen what do you mean by graphic stream?

**Comment by isopen** [comment]
UI thread

**Pull request merged**
