### PR TITLE
Add callback-based logging stream

### PR DESCRIPTION
**Pull request by ColonelThirtyTwo**
Allows the user of the library to specify log functions, allowing the library to hook into other logging solutions.

### CODE REVIEW

**Comment by levlam** [comment]
Thanks, @ColonelThirtyTwo!
This is a needed feature, a good way to add it and a good implementation. But I planned to add the feature in a different way though. TDLib already has the ability to hook fatal errors using `td_set_log_fatal_error_callback` and this new feature effectively extends that ability. I planned to allow log lines hooking in the same way, allowing the callback to receive all log messages. Then the same behavior would be achieved by setting the callback and setting the log stream to `logStreamEmpty`.

**Comment by ColonelThirtyTwo** [comment]
Changing `td_set_log_fatal_error_callback` would break API+ABI compatibility. IDK how much that matters to you though.

**Comment by levlam** [comment]
@ColonelThirtyTwo This is the reason, why the full replacement is planned only in TDLib 2.0, and for some time there should be two callback functions.

**Comment by ColonelThirtyTwo** [comment]
If that is the case, are you willing to merge this?

**Comment by levlam** [comment]
The feature will be added but in a different way, such as only one callback function is required for both log hooking and handling of fatal errors. The proposed changes will not be merged by that reason, but they are good by themselves and they can be used in the meanwhile.

**Comment by ColonelThirtyTwo** [comment]
So what is the ETA for tdlib 2 then? If it's going to be any significant length of time, you may as well merge this so we can use it. It's not like its going to be an issue moving forward since V2 is not going to be backwards-compatible anyway.

**Comment by levlam** [comment]
There is no ETA for future releases, but definitely 2.0 will not be released soon.

It's a good point that 2.0 will be anyway backward-incompatible, but if this pull request is merged, then there will be a point in time, when three callback functions, two of which are deprecated, exist. It is better to skip this state and have only one new callback function and one deprecated fatal error callback function.

**Comment by r3z4r3557** [comment]
Hii

**Review by VChernomYA — COMMENTED** [review]
[]()

**Comment by levlam** [comment]
Finally, the function `td_set_log_message_callback` was added to TDLib 1.7.5, which allows to intercept all TDLib log entries. Combined with `logStreamEmpty` it allows to completely redirect TDLib's log anywhere. This addition supersedes the proposed changes.

**Pull request closed without merging**
