### PR TITLE
Fix file to run with powershell or bash

### PR DESCRIPTION
**Pull request by davtur19**

### CODE REVIEW

**Comment by levlam** [comment]
It works for me in mintty with `./bootstrap-vcpkg.bat`. Which terminal are you using that requires running `./bootstrap-vcpkg.sh`?

**Comment by davtur19** [comment]
Ubuntu bash on windows

```sh
davide@Desktop-Davide:/mnt/c/Users/Davide/Downloads/td/vcpkg$ ./bootstrap-vcpkg.bat
./bootstrap-vcpkg.bat: line 1: @echo: command not found
& : Impossibile caricare il modulo '%~dp0scripts'. Per ulteriori informazioni, eseguire 'Import-Module %~dp0scripts'.
In riga:1 car:6
+ & {& '%~dp0scripts\bootstrap.ps1' %*}
+      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (%~dp0scripts\bootstrap.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoLoadModule```

**Comment by levlam** [comment]
To receive build instructions for Windows Subsytem for Linux (WSL) you need to choose Linux as operating system and then choose your distro. Instructions for Windows will be anyway wrong there, because WSL doesn't have Windows environment.

**Comment by davtur19** [comment]
Oh sorry, thank you.

**Pull request closed without merging**
