### PR TITLE
 Add Object Pascal language to readme

### PR DESCRIPTION
**Pull request by dieletro**
I followed the model of the other languages ​​and I hope it can be done like this

### CODE REVIEW

**Comment by dieletro** [comment]
I closed it like other Pull Requests, because I understood that that way it would not be possible to make the change!

**Comment by levlam** [comment]
Thanks, @dieletro! This is very good now and will be merged.

**Comment by dieletro** [comment]
Good, in the meantime I'm adding new examples to my repository.

**Comment by dieletro** [comment]
> Thanks, @dieletro! This is very good now and will be merged.

Hello, could you tell me if there is any forecast for the change of the readme with the Object Pascal that I suggested?

**Comment by levlam** [comment]
@dieletro No. The pull request will be accepted next time I am able to push changes to Github.

**Pull request merged**
