### PR TITLE
Fixes for cross-compilation with mingw on Linux host

### PR DESCRIPTION
**Pull request by ars3niy**

### CODE REVIEW

**Comment by levlam** [comment]
@ars3niy Thanks!

Currently, the names of headers and DLLs are correctly specified. Changing it could cause some issues on Windows like in https://ci.appveyor.com/project/piscisaureus/wepoll/builds/33115905/job/ihio591255g4f9r6#L163. The warning seems to be the only possible issue, but I would prefer safer #ifdef conditional includes and check for Linux + MinGW in CMakeLists.txt anyway.

The change of CMAKE_HOST_WIN32 instead of WIN32 looks correct.

Could you explain, why there are linking errors if Windows libraries are specified before OpenSSL/zlib libraries?

**Comment by ars3niy** [comment]
> Changing it could cause some issues on Windows like in https://ci.appveyor.com/project/piscisaureus/wepoll/builds/33115905/job/ihio591255g4f9r6#L163.

Oh great, so mingw uses different case for headers (and perhaps libraries) compared to other windows SDKs. Headers in mingw on windows is also all-lower-case.

If you think those #ifdef are worth it, you can add them, but actually I don't mind doing things like `sed 's/WinSock2.h/winsock2.h/;s/WS2tcpip.h/ws2tcpip.h/;s/MSWSock.h/mswsock.h/;s/Windows.h/windows.h/' -i tdutils/td/utils/common.h` when building tdlib.

> Could you explain, why there are linking errors if Windows libraries are specified before OpenSSL/zlib libraries?

It's because openssl libcrypto itself links against those same windows socket libraries. So at least when using static openssl library, socket libraries have to go after libcrypto on linker command line when using the linker that you got on Linux. This library order is a thing on Linux in general, and apparently it applies to cross-compilation with mingw as well.

That patch only makes tdlib compile, however. To get a program using tdlib to compile, I also had to add socket libraries to every tdlib component that links against libcrypto, which doesn't look all that pretty any more:

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index ac9efadb..0c313b6f 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -777,6 +777,9 @@ add_library(tdcore STATIC ${TDLIB_SOURCE})
 target_include_directories(tdcore PUBLIC $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}> $<BUILD_INTERFACE:${TL_TD_AUTO_INCLUDE_DIR}>)
 target_include_directories(tdcore SYSTEM PRIVATE ${OPENSSL_INCLUDE_DIR})
 target_link_libraries(tdcore PUBLIC tdapi tdactor tdutils tdnet tddb PRIVATE ${OPENSSL_CRYPTO_LIBRARY} ${CMAKE_DL_LIBS} ${ZLIB_LIBRARIES})
+if (WIN32)
+  target_link_libraries(tdcore PRIVATE ws2_32 mswsock normaliz)
+endif()
 
 if (NOT CMAKE_CROSSCOMPILING)
   add_dependencies(tdcore tl_generate_common)
diff --git a/sqlite/CMakeLists.txt b/sqlite/CMakeLists.txt
index c8968576..a5f72522 100644
--- a/sqlite/CMakeLists.txt
+++ b/sqlite/CMakeLists.txt
@@ -21,6 +21,9 @@ add_library(tdsqlite STATIC ${SQLITE_SOURCE})
 target_include_directories(tdsqlite PUBLIC $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}>)
 target_include_directories(tdsqlite SYSTEM PRIVATE ${OPENSSL_INCLUDE_DIR})
 target_link_libraries(tdsqlite PRIVATE ${OPENSSL_CRYPTO_LIBRARY} ${CMAKE_DL_LIBS} ${ZLIB_LIBRARIES})
+if (WIN32)
+  target_link_libraries(tdsqlite PRIVATE ws2_32 mswsock normaliz)
+endif()
 target_compile_definitions(tdsqlite PRIVATE
   -DSQLITE_DEFAULT_MEMSTATUS=0
   -DSQLITE_OMIT_LOAD_EXTENSION
diff --git a/tdnet/CMakeLists.txt b/tdnet/CMakeLists.txt
index e54eecc0..9fafbecd 100644
--- a/tdnet/CMakeLists.txt
+++ b/tdnet/CMakeLists.txt
@@ -60,6 +60,7 @@ target_link_libraries(tdnet PRIVATE ${OPENSSL_CRYPTO_LIBRARY})
 
 if (WIN32)
   target_link_libraries(tdnet PRIVATE crypt32)
+  target_link_libraries(tdnet PRIVATE ws2_32 mswsock normaliz)
 endif()
 
 install(TARGETS tdnet EXPORT TdTargets
```

**Comment by ars3niy** [comment]
Actually, the library order issue can be solved without modifying cmake scripts, so removing the third commit.

**Comment by levlam** [comment]
@ars3niy That's exactly what I expected about linking errors, because if all dependencies are correctly specified, then order of CMake statements shouldn't matter. So the issue must be fixed by correctly specifying dependencies of OpenSSL and tdsqlite as you did.

**Comment by ars3niy** [comment]
So right now I'm doing this, and it works:
```
cmake \
    -DOPENSSL_FOUND=True \
    -DOPENSSL_SSL_LIBRARY="-Wl,-Bstatic -lssl -Wl,-Bdynamic -lws2_32" \
    -DOPENSSL_CRYPTO_LIBRARY="-Wl,-Bstatic -lcrypto -Wl,-Bdynamic -lws2_32" \
```

This is actually a good way to do it. For example when using something like GTK, one has to link with `-lgtk-2 -lglib-2.0`, which is typically accomplished by having a single variable GTK_LIBRARIES that ends up being equal to `"-lgtk-2 -lglib-2.0"`.

**Comment by ars3niy** [comment]
I would just like to have the CMAKE_HOST_WIN32 thing in for now.

**Comment by levlam** [comment]
I will accept the CMAKE_HOST_WIN32 change.

**Comment by ars3niy** [comment]
Well, that's what is in the pull request now.

**Comment by levlam** [comment]
@ars3niy Yes, but due to the way the source code is published, pull requests can be accepted only after the latest code is pushed to Github. I hope this wiil be possible soon.

**Comment by levlam** [comment]
@ars3niy Does OpenSSL and SQLite use only ws2_32 library? I expected OpenSSL to use at least mswsock and Crypt32 also.

**Comment by ars3niy** [comment]
With the `-DOPENSSL_SSL_LIBRARY=...` workaround, link library order for a project that uses tdlib ends up like this:

```
../../deps/pidgin-2.13.0/libpurple/libpurple.dll.a
../../deps/win32-dev/gtk_2_0-2.14/lib/libglib-2.0.dll.a
../../deps/win32-dev/gtk_2_0-2.14/lib/libgthread-2.0.dll.a
../../deps/win32-dev/libwebp-1.1.0/install/usr/local/lib/libwebp.a
../../deps/win32-dev/libpng-1.6.37/install/usr/local/lib/libpng16.a
fmt/libfmt.a rlottie/librlottie.a
/w/work/tdlib-purple/deps/win32-dev/gtk_2_0-2.14/lib/libintl.dll.a
/w/bin/td/win32/install/usr/local/lib/libtdclient.a
/w/bin/td/win32/install/usr/local/lib/libtdcore.a
/w/bin/td/win32/install/usr/local/lib/libtdnet.a -Wl,-Bstatic -lssl
-Wl,-Bdynamic -lcrypt32 /w/bin/td/win32/install/usr/local/lib/libtddb.a
/w/bin/td/win32/install/usr/local/lib/libtdactor.a
/w/bin/td/win32/install/usr/local/lib/libtdsqlite.a
/w/bin/td/win32/install/usr/local/lib/libtdutils.a -Wl,-Bstatic
-lcrypto -Wl,-Bdynamic -lws2_32 -lmswsock -lnormaliz -Wl,-Bstatic -lz
-Wl,-Bdynamic -Wl,--no-undefined -lkernel32 -luser32 -lgdi32 -lwinspool
-lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 -Wl,-Bstatic
-lpthread -Wl,-Bdynamic
```

`-lcrypt32` is before `-lcrypto` but it doesn't seem to matter (it's after `-lssl` though, that might matter). `-lmswsock` is near the end already without any workarounds.

**Comment by levlam** [comment]
You have normaliz linked to libcrypto, but I don't think that it is actually used there.

Also, do you know where from -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 are coming and why pthread is linked in Windows binary?

**Comment by ars3niy** [comment]
> Do you know where from -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 are coming

That's from Windows-GNU.cmake that came with my cmake:

`set(CMAKE_C_STANDARD_LIBRARIES_INIT "-lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32")`

Windows-MSVC.cmake can put into place something similar, depending on exact platform and MSVC version.

> and why pthread is linked in Windows binary?

That's just a mingw thing. If I don't put -lpthread on linker command line, mingw will link against that libwinpthread.dll of his anyway – dynamically, and then my binary will not be trivially redistributable. So in CMakeLists.txt **for my project** I added roughly speaking

`set (CMAKE_CXX_STANDARD_LIBRARIES "${CMAKE_CXX_STANDARD_LIBRARIES} -Wl,-Bstatic
-lpthread -Wl,-Bdynamic")`

some place, and my binary works without having to have a mingw dll by its side.

If I were building tdlib as a .dll then it would have acquired the same libwinpthread.dll dependency, but I'm building a static library so I don't have to worry about that.

**Comment by levlam** [comment]
@ars3niy Could you check that all mensioned by you issues are fixed in the latest TDLib version and cross-compilation using MinGW under Linux works without source code changes?

**Comment by ars3niy** [comment]
Yes the link order issue is gone, thanks.

**Comment by levlam** [comment]
Included file name case and linked libraries file name case was also fixed for MinGW.

**Comment by ars3niy** [comment]
Right, indeed it was.

**Comment by levlam** [comment]
Thanks, @ars3niy!

**Pull request merged**
