### PR TITLE
Improve appearance of build instructions generator

### PR DESCRIPTION
**Pull request by Mammad900**
Improved formatting, colors and other appearance-related things.  
Also added a dark mode which is activated based on the user's system preferences.

Before:
image

After: 
image
image

### CODE REVIEW

**Review by Muaath5 — APPROVED** [review]
Almost all of commits are CSS editing.
The only thing was edited in Javascript is using `<ul>` instead of `\n`
And `<code>` instead of `<pre>`.

It supports dark mode, And uses CSS Variables.

**Comment by Pearlminima** [comment]
> Almost all of commits are CSS editing.
> 
> The only thing was edited in Javascript is using `<ul>` instead of `\n`
> 
> And `<code>` instead of `<pre>`.
> 
> 
> 
> It supports dark mode, And uses CSS Variables.

**Comment by cavallium** [comment]
`<meta name="viewport" content="width=device-width, initial-scale=1">` is missing

**Comment by cavallium** [comment]
Also `<meta charset="UTF-8">` and `lang=en` are missing

**Pull request merged**
