### PR TITLE
build pkg-config files for tdjson and tdjson_static

### LINKED ISSUE #1067: generate pkgconfig file
Some build tools (cabal for example) relies on pkg-config to discover c libraries. Would it be possible to generator this file when building tdlib?

### PR DESCRIPTION
**Pull request by Marukesu**
Fix #1067 
Supersede #867

### CODE REVIEW

**Comment by levlam** [comment]
Thanks, @Marukesu!

This is substantially better than the previous pull request, but still there are a lot of drawbacks with this approach.

For example, if the compiler is clang, then libstdc++ still can be used as a standard C++ library. Also, it will be hard to manually mantain the "*.pc.in" files. The right approach would be to get the list of dependencies from CMake and convert it to pkg-config format.

Also, from the pkg-config point of view it seems reasonable to have a separate `.pc` file for all CMake targets, not only for `tdjson` and `tdjson_static`. And this is another reason, why they should be generated automatically using known to CMake data.

**Comment by levlam** [comment]
The mentioned approach has been tried in https://stackoverflow.com/questions/44292462/how-to-auto-generate-pkgconfig-files-from-cmake-targets. The function implemented there needs a lot of improvements to generate a good pkg-config file, but the approach itself is right and much more flexible.

**Comment by Marukesu** [comment]
Ok, now it's generating the files from the `generate_pkgconfig` function, it's linking to non-targets dependencies via the `Libs.private` field and Targets dependencies via `Requires.private` field.

for example, tdjson_static generates:
```
prefix=/usr/local
includedir=${prefix}/include
libdir=${prefix}/lib

Name: tdjson_static
Description: Telegram Library - Json Interface (static)
Version: 1.6.9

CFlags: -I${includedir}
Libs: -L${libdir} -ltdjson_static
Requires.private: tdjson_private
```
with pkg-config output:
```
$ pkg-config --cflags --libs --static tdjson_static
-I/usr/local/include -L/usr/local/lib -ltdjson_static -ltdjson_private -ltdclient -ltdcore -lcrypto -ldl -lz -ltdapi -ltdnet -ldl -lz -lssl -lcrypto -ltddb -ltdactor -ltdsqlite -lcrypto -ldl -lz -ltdutils -pthread -lcrypto -ldl -lz
```

since `libc++/libstdc++` are not a declared dependency it's not included in the files.

**Comment by levlam** [comment]
Now I agree with the approach. I will test this and likely accept. Could you squash the commits and force push?

**Comment by levlam** [comment]
Thanks, @Marukesu! Very good job.

**Comment by levlam** [comment]
@Marukesu I identified and fixed some issues with the implementation. Now it seems to correctly handle most cases.

Now pkg-config output is:
```
$ pkg-config --cflags --libs --static tdjson_static
-I/usr/local/include -L/usr/local/lib -ltdjson_static -ltdjson_private -ltdclient -ltdcore -l:libcrypto.so -ldl -l:libz.so -ltdapi -ltdnet -l:libssl.so -l:libcrypto.so -ldl -l:libz.so -ltddb -ltdactor -ltdsqlite -l:libcrypto.so -ldl -l:libz.so -ltdutils -pthread -l:libcrypto.so -ldl -l:libz.so
```

The lack of `libc++/libstdc++` in the dependencies isn't a big issue, because if the code is built using `g++/clang++`, it will be added automatically.

**Pull request merged**
